services:
  db:
    image: postgres:17-alpine
    container_name: stnet-database
    environment:
      - POSTGRES_PASSWORD=123456
      - TZ=Asia/Bangkok
    ports:
      - 5432:5432
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - stnet

networks:
  stnet: {}
